#!/usr/bin/env ruby

require 'pathname'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../gems.rb', Pathname.new(__FILE__).realpath)
require 'bundler/setup'

require 'awshark'

Awshark::Cli.start(ARGV)
